version: '3.8'

services:
    db:
        image: pgvector/pgvector:pg16
        container_name: auth_postgres
        restart: always

        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}

        ports:
            - ${DB_PORT}:5432

        volumes:
            - pgdata:/var/lib/postgresql/data

    ollama:
        image: ollama/ollama
        container_name: ollama
        restart: always

        ports:
            - ${OLLAMA_PORT:-11434}:11434

        volumes:
            - ollama_data:/root/.ollama
    ollama-init:
        image: ollama/ollama
        depends_on:
            - ollama
        environment:
            - OLLAMA_HOST=ollama:11434
        entrypoint: ['ollama', 'pull', '${OLLAMA_EMBED_MODEL:-nomic-embed-text}']
        restart: 'no'

volumes:
    pgdata:
    ollama_data:
